version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  nginx:
    image: ubuntu/nginx:latest
    restart: always
    ports:
      - "3050:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server
  db:
    image: postgres:17.3-alpine
    container_name: postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./data/uuid-data.sql:/docker-entrypoint-initdb.d/uuid-data.sql:ro
volumes:
  db:
    driver: local